@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODYxOWM4OTgzZjI1YzMzNzE5NjUyN2EiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MTIyNzU3OCwiZXhwIjoxNzUzODE5NTc4fQ.UdbRD2mvzQyNmGADbSFjQmsODsg4E6cqlTnwPZ7Pksk
### Registro de usuario
POST http://localhost:8000/api/users/register
Content-Type: application/json

{
  "name": "Juan",
  "surnames": "Pérez",
  "email": "alvarodiezz16@gmail.com",
  "password": "securePass123.",
  "phoneNumber": "123456789"
}

### Validación de email (requiere token de auth)
PUT http://localhost:8000/api/users/validation-mail
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "code": "184355"
}

###

### Validación de email para recuperar contraseña
POST http://localhost:8000/api/users/validation
Content-Type: application/json

{
  "email": "alvarodiezz16@example.com",
  "code": "646216"
}

###

### Login de usuario
POST  https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/login
Content-Type: application/json

{
  "email": "alvarodiezz16@gmail.com",
  "password": "securePass123."
}
