@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODYxOWM4OTgzZjI1YzMzNzE5NjUyN2EiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MTIyNzU3OCwiZXhwIjoxNzUzODE5NTc4fQ.UdbRD2mvzQyNmGADbSFjQmsODsg4E6cqlTnwPZ7Pksk

@host = https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app

### Añadir gasolinera a favoritos
POST {{host}}/api/gasstation/favorite
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "6238"
}

### Eliminar gasolinera de favoritos
DELETE {{host}}/api/gasstation/favorite
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "6238"
}

### Añadir o actualizar reseña
POST {{host}}/api/gasstation/review
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "6238",
  "rating": 4,
  "comment": "Buena atención y precios competitivos"
}

### Eliminar reseña
DELETE {{host}}/api/gasstation/review
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "6238"
}

### Obtener gasolinera guardada
GET {{host}}/api/gasstation/saved
Authorization: Bearer {{token}}

### Dar like
PUT {{host}}/api/gasstation/6238/reviews/686038bdde2eecd4cfb2233c/like
Authorization: Bearer {{token}}

### Dar like
PUT {{host}}/api/gasstation/6238/reviews/686038bdde2eecd4cfb2233c/dislike
Authorization: Bearer {{token}}
