@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI4OGY4MWE5NDYxNGYzZjVkZjM3ODEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDc0ODkwMzIsImV4cCI6MTc1MDA4MTAzMn0.Qaa_ufRe9KqFpZpuGe1w7ju2HgbgZmK7eal1qbUg0n0
@host = http://localhost:8000

### Añadir gasolinera a favoritos
POST {{host}}/api/gasstation/favorite
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "10483"
}

### Eliminar gasolinera de favoritos
DELETE {{host}}/api/gasstation/favorite
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "12345"
}

### Añadir o actualizar reseña
POST {{host}}/api/gasstation/review
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "12345",
  "rating": 4,
  "comment": "Buena atención y precios competitivos"
}

### Eliminar reseña
DELETE {{host}}/api/gasstation/review
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEESS": "12345"
}

### Obtener gasolinera con historial
GET {{host}}/api/gasstation/12345
Authorization: Bearer {{token}}
