### Obtener la estación de servicio más cercana
GET http://localhost:8000/api/maps/fuelStationCoordinates?latitude=40.464015&longitude=-3.457103&radius=5
Content-Type: application/json

### Obtener una estación de servicio por ID
GET https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/maps/fuelStationId/10000
Content-Type: application/json

### Obtener múltiples estaciones de servicio por ID (usando body)
POST https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/maps/fuelStationId
Content-Type: application/json

{
    "fuelStationIds": ["1", "2", "3"]
}

### Obtener múltiples estaciones de servicio por ID (usando query params)
POST https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/maps/fuelStationId?fuelStationIds=["12","100","7"]
Content-Type: application/json

### Obtener estaciones de servicio más cercanas
GET http://localhost:8000/api/maps/fuelStationCoordinates?latitude=40.4168&longitude=-3.7038&radius=10&limit=5&fuelType=priceDiesel&brand=REPSOL
Accept: application/json
