@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI4OGY4MWE5NDYxNGYzZjVkZjM3ODEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTAyNDI3MTAsImV4cCI6MTc1MjgzNDcxMH0.4Qp7AN1BpFoE2GNf9Xvi_Cub4dx6uLovcDkGdRGOloE
@admin_token =  



### RECOVER TOKEN TO VALIDATE PASSWORD
PUT http://localhost:8000/api/users/recover-psswd
Content-Type: application/json

{
  "email": "test@example.com"
}

### VALIDATE EMAIL TO RECOVER PASSWORD
PUT http://localhost:8000/api/users/validation-psswd
Content-Type: application/json

{
  "email": "test@example.com",
  "code": "123456"
}

### GET USERs PROFILE (requires token)
GET http://localhost:8000/api/users/profile
Authorization: Bearer {{token}}

### UPDATE USERs (requires token)
PUT http://localhost:8000/api/users/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Nuevo Nombre"
}

### CHANGE PASSWORD (requires token)
PUT http://localhost:8000/api/users/changepswd
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentPassword": "securePass123.",
  "newPassword": "NuevoPassword456."
}

### DELETE USERs (requires token)
DELETE http://localhost:8000/api/users?logic=true
Authorization: Bearer {{token}}

### RESTORE USERs (requires admin token)
PATCH http://localhost:8000/api/users/restore/USERs_ID
Authorization: Bearer {{admin_token}}

### ADD IMAGE TO USERs (requires token)
PATCH http://localhost:8000/api/users/addimage
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="cerberus.png"
Content-Type: image/jpeg

< ./images/cerberus.png
--Boundry--
