### Registro de usuarios
POST https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Menganito",
    "email": "menganitohernandez@test.com",
    "password": "n0ki3er.0proVa23lc$dIgo"
}

###

POST https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Pepito",
    "email": "peitoperez@test.com",
    "password": "Dan0nino.",
}

###

POST https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Almudena",
    "email": "almudenagimenez@test.com",
    "password": "holaef.A1a"
}

### Inicio de sesión
POST https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "menganitohernandez@test.com",
    "password": "n0ki3er.0proVa23lc$dIgo"
}

### Inicio de sesión ADMIN
POST https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "peitoperez@test.com",
    "password": "3stoN0.esuN4contr4s3ña"
}

### Obtener todos los usuarios (solo admin)
GET https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2EyNzA0Y2RjMGUwZDYyNGQ3ODBmMmYiLCJyb2xlIjoidXNlciIsImlhdCI6MTczODY5ODgyOSwiZXhwIjoxNzM4Nzg1MjI5fQ.DxhAMv_RsR1UE3DryhdY0aivARRlo3sjQixG4H7CZ2M

### Obtener usuario por ID
GET https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/6717c999d065ac2a9d4f0b94
Content-Type: application/json
Authorization: Bearer <TOKEN_VALIDO>

### Actualizar usuario (solo el propio o admin)
PUT https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/673cb1c25c3fdb2aaf951ba4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer <TOKEN_VALIDO>

{
    "name": "Menganito",
    "email": "menganitohernandez@test.com",
}
s
### Borrado lógico de usuario
DELETE https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/6717ca80d065ac2a9d4f0b9f?logic=true
Content-Type: application/json
Authorization: Bearer <TOKEN_VALIDO>

### Restaurar usuario eliminado lógicamente
PUT https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/restore/6717ca80d065ac2a9d4f0b9f
Content-Type: application/json
Authorization: Bearer <TOKEN_VALIDO>

### Eliminación física de usuario (solo admin)
DELETE https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/671fb460afda9b6f5ac5576e?logic=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2EyNzA0Y2RjMGUwZDYyNGQ3ODBmMmYiLCJyb2xlIjoidXNlciIsImlhdCI6MTczODY5ODgyOSwiZXhwIjoxNzM4Nzg1MjI5fQ.DxhAMv_RsR1UE3DryhdY0aivARRlo3sjQixG4H7CZ2M
