@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODYxOWM4OTgzZjI1YzMzNzE5NjUyN2EiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MTIyNzU3OCwiZXhwIjoxNzUzODE5NTc4fQ.UdbRD2mvzQyNmGADbSFjQmsODsg4E6cqlTnwPZ7Pksk



### RECOVER TOKEN TO VALIDATE PASSWORD
PUT http://localhost:8000/api/users/recover-psswd
Content-Type: application/json

{
  "email": "test@example.com"
}

### VALIDATE EMAIL TO RECOVER PASSWORD
PUT http://localhost:8000/api/users/validation-psswd
Content-Type: application/json

{
  "email": "test@example.com",
  "code": "123456"
}

### GET USERs PROFILE (requires token)
GET http://localhost:8000/api/users/profile
Authorization: Bearer {{token}}

### UPDATE USERs (requires token)
PUT http://localhost:8000/api/users/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Nuevo Nombre"
}

### CHANGE PASSWORD (requires token)
PUT http://localhost:8000/api/users/changepswd
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currentPassword": "securePass123.",
  "newPassword": "NuevoPassword456."
}

### DELETE USERs (requires token)
DELETE http://localhost:8000/api/users
Authorization: Bearer {{token}}

### RESTORE USERs (requires admin token)
PATCH http://localhost:8000/api/users/restore/USERs_ID
Authorization: Bearer {{admin_token}}

### ADD IMAGE TO USERs (requires token)
PATCH https://underlying-regan-immune-mvc-a0b35a6c.koyeb.app/api/users/addimage
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="spidernino.png"
Content-Type: image/jpg

< ./images/spidernino.jpg
--Boundry--
