@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODYxOWM4OTgzZjI1YzMzNzE5NjUyN2EiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MTIyNzU3OCwiZXhwIjoxNzUzODE5NTc4fQ.UdbRD2mvzQyNmGADbSFjQmsODsg4E6cqlTnwPZ7Pksk
@vehicleId = 685295f16655a420928e3588

### Agregar vehículo
POST http://localhost:8000/api/vehicles
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "brand": "Toyota",
  "model": "Corolla",
  "year": 2020,
  "fuelCapacity": 50,
  "fuelType": "petrol95",
  "vehicleType": "car",
  "favoriteGasBrand": "Repsol",
  "default": true
}

### Actualizar vehículo 
PUT http://localhost:8000/api/vehicles/vehicleId
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "brand": "Toyota",
  "model": "Corolla Hybrid",
  "year": 2021,
  "fuelCapacity": 45,
  "fuelType": "petrol95",
  "vehicleType": "car",
  "favoriteGasBrand": "Repsol",
  "default": false
}

### Eliminar vehículo 
DELETE http://localhost:8000/api/vehicles/vehicleId
Authorization: Bearer {{token}}

###
PATCH http://localhost:8000/api/vehicles/68615959e83ae338c462dfab/image
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/jpg

< ./images/image.jpg
--Boundry--